### ISSUE TITLE
Can i add my 2 articles in this guidelines readme

### ISSUE THREAD

**Issue by srsandy** [ashokdey/guidelines#4]
1. [Prototype in JS](https://www.codementor.io/sandeepranjan2007/prototype-in-javascipt-knbve0lqo)
2. [EventEmitter() in NodeJS ](https://gist.github.com/srsandy/9e27dbfa3d2086aedda964a67742c140)

Thank You. !

**Comment by ashokdey** [comment]
Thanks for taking interest @srsandy, this is not about concepts here, it's more about how to do things in the right way.

Hence your articles on JavaScript concepts will not be added here. I would encourage you to come up with some good practices.
